# Workflow will publish a Python package to PyPI when a new release is created

name: Upload Python Package

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Archive the dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
    - name: Download the dist folder from the build job
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
